import "./_styles/styles.scss";

import type { Metadata } from "next";

import { MainLayout } from "@widgets/layouts/main/ui";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default MainLayout;
